name: stable_nerf
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pytorch-cuda=11.8
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pip
  - pip:
    - opencv-python
    - ninja
    - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
    - git+https://github.com/rahul-goel/fused-ssim/
    - submodules/raymarching
    - matplotlib
    - plyfile
    - tqdm
    - diffusers
    - transformers 
    - accelerate
    - einops
    - pathlib

